#!/bin/sh
TOP="$(cd $(dirname "$0")/../..; pwd)"

unset EDMDATAFILES

export EDMDATAFILES="${EDMDATAFILES}:${TOP}/../../zebraApp/opi/edl"
export EDMDATAFILES="${EDMDATAFILES}:/usr/lib/epics/op/edl"

OPTS="-x -eolc -noedit"
export PATH=${EDMDATAFILES}:${PATH}
edm ${OPTS} -m "zebra=${1:-TESTZEBRA}" zebra.edl
