/* This file was automatically generated on Tue 24 Feb 2015 16:11:07 GMT from
 * source: /dls_sw/prod/R3.14.12.3/support/zebra/1-13/etc/makeIocs/test.xml
 * 
 * *** Please do not edit this file: edit the source file instead. ***
 *  */
#include "epicsExit.h"
#include "epicsThread.h"
#include "iocsh.h"

int main(int argc, char *argv[])
{
    if(argc>=2) {
        iocsh(argv[1]);
        epicsThreadSleep(.2);
    }
    iocsh(NULL);
    epicsExit(0);
    return 0;
}

