# This file was automatically generated on Tue 24 Feb 2015 16:11:07 GMT from
# source: /dls_sw/prod/R3.14.12.3/support/zebra/1-13/etc/makeIocs/test.xml
# 
# *** Please do not edit this file: edit the source file instead. ***
# 
cd ../..
< envPaths


epicsEnvSet "EPICS_TS_MIN_WEST", '0'


# Loading libraries
# -----------------

# Device initialisation
# ---------------------



dbLoadDatabase "dbd/test.dbd"
test_registerRecordDeviceDriver(pdbbase)

drvAsynSerialPortConfigure("ty_zebra", "/dev/ttyUSB0", 100, 0, 0)
asynSetOption("ty_zebra", 0, "baud", "115200")
asynSetOption("ty_zebra", 0, "parity", "None")
asynSetOption("ty_zebra", 0, "stop", "1")
asynSetOption("ty_zebra", 0, "bits", "8")

#zebraConfig(Port, SerialPort, MaxPosCompPoints)
zebraConfig("ZEBRA", "ty_zebra", 100000)

# Final ioc initialisation
# ------------------------

dbLoadRecords 'db/test_expanded.db' "ZEBRAPREFIX=$(ZEBRAPREFIX)"
iocInit
